# https://docs.confluent.io/platform/current/quickstart/ce-docker-quickstart.html
# To run this docker-compose you will probably need to increase your memory docker can use.
#   - Open your Docker Desktop App > Preferences > Resources > Advanced > Increase the memory allocated
---
version: '2'

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres
    container_name: expertise-postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DATABASE=postgres
      - POSTGRES_WAL_LEVEL=logical
    ports: 
      - "5432:5432"
  
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: expertise-redis
    ports: 
      - "6379:6379"
